# Generated by Django 6.0 on 2025-12-23 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Event Title')),
                ('description', models.TextField(blank=True, verbose_name='Event Description')),
                ('date', models.DateTimeField(verbose_name='Event Date and Time')),
                ('location', models.CharField(max_length=255, verbose_name='Event Location')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Event Creation Date and Time')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Event Last Update Date and Time')),
            ],
            options={
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='EventRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registered_at', models.DateTimeField(auto_now_add=True, verbose_name='Registration Date and Time')),
            ],
            options={
                'ordering': ['-registered_at'],
            },
        ),
    ]
